"""Generate ``src/baltic/_catalog.py`` from the vendored API metadata.

Run via ``make catalog``. The report IDs come from the documented ``id`` enum in
``spec/openapi.json``; the titles, resolutions and categories that make them
usable come from ``spec/reports.json``. The client itself is hand-written: the
API has two endpoints, so there is nothing worth generating there.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

HEADER = '''"""Catalog of the reports the BTD API can export.

Generated by ``src/gen_catalog.py`` from ``spec/``. Do not edit.
"""

from __future__ import annotations

from .models import Report

# The API rejects an export-multiple request with more report IDs than this.
MAX_REPORTS_PER_REQUEST = {max_reports}

REPORTS: tuple[Report, ...] = (
'''


def report_ids(spec: dict[str, Any]) -> list[str]:
    parameters = spec["paths"]["/api/v1/export"]["get"]["parameters"]
    for parameter in parameters:
        if parameter["name"] == "id":
            return list(parameter["enum"])
    raise SystemExit("no 'id' parameter found in spec/openapi.json")


def categories(tags: list[int], terms: dict[int, dict[str, Any]]) -> tuple[str, ...]:
    """Resolve taxonomy term IDs to their labels, ancestors included."""
    labels: list[str] = []
    for tag in tags:
        term = terms.get(tag)
        if term is None:
            continue
        for ancestor in term["path"]:
            label = terms[ancestor]["label"]
            if label not in labels:
                labels.append(label)
    return tuple(labels)


def render(spec: dict[str, Any], catalog: dict[str, Any]) -> str:
    terms = {term["id"]: term for term in catalog["tags"]}
    nodes = {node["machine_name"]: node for node in catalog["nodes"]}
    max_reports = catalog.get("limits", {}).get("limit", 4)

    lines = [HEADER.format(max_reports=max_reports)]
    for report_id in sorted(report_ids(spec)):
        node = nodes.get(report_id, {})
        title = str(node.get("title", report_id)).strip()
        resolutions = tuple(node.get("resolutions") or ())
        lines.append("    Report(")
        lines.append(f"        id={report_id!r},")
        lines.append(f"        title={title!r},")
        lines.append(f"        resolutions={resolutions!r},")
        lines.append(f"        categories={categories(node.get('tags', []), terms)!r},")
        lines.append("    ),")
    lines.append(")\n")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spec", type=Path, default=Path("spec/openapi.json"))
    parser.add_argument("--reports", type=Path, default=Path("spec/reports.json"))
    parser.add_argument("--out", type=Path, default=Path("src/baltic/_catalog.py"))
    args = parser.parse_args()

    spec = json.loads(args.spec.read_text(encoding="utf-8"))
    catalog = json.loads(args.reports.read_text(encoding="utf-8"))["data"]
    args.out.write_text(render(spec, catalog), encoding="utf-8")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
